### ISSUE TITLE
Password Detection Testing

### ISSUE THREAD

**Issue by Terlen** [Terlen/IFT401_Capstone#2]
Ensure password detection works across multiple webpages and layouts.

**Comment by rayan90** [comment]
Got it.

**Comment by Terlen** [comment]
I've found two sites that don't yet work fully with password detection.

1.  trycookin.com is a strange case, it works when the user navigates directly to trycookin.com/login/ but fails when the user navigates through the site to reach the login page. Suspect this is Javascript related, but needs further testing.

2. mangahere.co is certainly Javascript related. The login dialog is hidden until revealed by a JS function. Password detection should be expanded to fit this case.

**Comment by Terlen** [comment]
Time for password detection testing is over, it now works reliably on many sites. Should be reopened if a problem is found.
