### ISSUE TITLE
Alert Page direction

### ISSUE THREAD

**Issue by bhcunit6** [Terlen/IFT401_Capstone#22]
Instead of forcing the user into options with their passwords, we are going to start moving more towards informing the user.

Red Options: Leave password as is. We will explain to the user why this is a poor choice.

Yellow Options: User takes steps to change the password on their own. They also have the option to whitelist either the detected phrase or the URL of the page where the password was detected.

Green Options: Gives the user access to their Facebook so that they can change their public information to private.

**Comment by Terlen** [comment]
Implemented with pull request #24
